workflow:
  rules:
    # can not be executed as part of merge request
    # this avoids weird pipeline behavior (rules:changes comparing to dev branch),
    # however might produce more job runs
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - when: always # Run pipeline in all other cases

# includes from the global ci-templates repository
include:
  - project: 'common/ci-templates'
    ref: main
    file: '/devops/container/build.yml'
  - project: 'common/ci-templates'
    ref: main
    file: '/devops/python/build-and-publish-pipeline.yml'

# optional - override the default values, if specified
variables:
  REGISTRY_BASE_URL: ${CI_REGISTRY_IMAGE}/mcpf
  # define a specific python version. Will be replaced in a future version by configuring pyenv in pyproject.toml
  PYTHON_VERSION: '3.10'
  # defined image for python testing - should be able to run all python stuff
  PYTHON_IMAGE: ${REGISTRY_BASE_URL}/test

stages:
  - provision
  - sast
  - test
  - build
  - publish

build-base-image:
  stage: provision
  needs: []
#  rules:
#    - changes:
#      - $PYTHON_WORKING_DIRECTORY/poetry.lock
#      - $PYTHON_WORKING_DIRECTORY/Dockerfile-base
  extends:
    - .kaniko-build-image
  variables:
    IMAGE_NAME: ${REGISTRY_BASE_URL}/base
    DOCKERFILE: Dockerfile-base
    WORKING_DIRECTORY: ${CI_PROJECT_DIR}/${PYTHON_WORKING_DIRECTORY}

build-test-image:
  stage: provision
  needs: []
#  rules:
#    - changes:
#      - $PYTHON_WORKING_DIRECTORY/poetry.lock
#      - $PYTHON_WORKING_DIRECTORY/Dockerfile-test
  extends:
    - .kaniko-build-image
  variables:
    IMAGE_NAME: ${REGISTRY_BASE_URL}/test
    DOCKERFILE: Dockerfile-test
    WORKING_DIRECTORY: ${CI_PROJECT_DIR}/${PYTHON_WORKING_DIRECTORY}

# Need duplication due to different working directory
python-test:
  needs: ["python-precommit-check"]
  stage: test
  script:
    - echo "This package is a meta package and does not contain any code to test."
    # Fake test results
    - echo '<?xml version="1.0"?><testsuites><testsuite errors="0" failures="0" name="No tests available" tests="0"></testsuite></testsuites>' > ${CI_PROJECT_DIR}/${PYTHON_WORKING_DIRECTORY}/python-junit.xml
    - echo '<?xml version="1.0"?><!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd"><coverage line-rate="1" branch-rate="0" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0" complexity="0" version="2.0.3" timestamp="1403301904999"/>' > ${CI_PROJECT_DIR}/${PYTHON_WORKING_DIRECTORY}/coverage.xml

publish-to-risc-pypi:
  needs: ["build-wheel-poetry"]
  stage: publish
  extends:
    - .publish-to-risc-pypi
    - .build-on-semversion
  variables:
    DIRECTORY: dist/*
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    TWINE_USERNAME: __token__
